### ISSUE TITLE
Favourite button doesn't change colour when selected

### ISSUE THREAD

**Issue by bastianvv** [CTalvio/Novachromic#2]
Jellyfin version: 10.6.4

First of all, I love your skins, so thanks for your awesome work.

I have an issue with the favourite button (:heart:), because it doesn't change colour when selected, thus, it's impossible to tell when a particular library object has been added to favourites or not.

This happens everywhere the favourite button is shown: libraries, movies, series, episodes, artists, albums, collections, playlists, and the *now playing* bar.

In the picture, which is the album details view, the highlighted song is marked as favourite, but the heart icon remains black.
![Screenshot_20210308_184221](https://user-images.githubusercontent.com/21223384/110385716-0bd88900-803e-11eb-82a4-c794f6aca03d.png)

Here a picture of the Monochromic skin in the same album.
![Screenshot_20210308_184550](https://user-images.githubusercontent.com/21223384/110386034-86a1a400-803e-11eb-90a6-065da840272f.png)

~~Notice also that in Novachromic there's no higlight colour in the heart icon when the cursor is hovering over it.~~ Ignore this, I just noticed the heart is highlighted by a white square

**Comment by CTalvio** [comment]
Ah!

This is due to the way I inverted the colors of icons from white to black. The same issue plagues the "seen" check-mark button. I'll look into making this work, thanks for the issue report!

**Comment by CTalvio** [comment]
Fixed
